### ISSUE TITLE
인증 로직 설계

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#8]
> 💡 아직 BE와 연결되지 않았으므로 실제 작동 테스트는 현재 단계에서 할 수 없음

- [x] Google OAuth 인증 방식 공부
- [x] Google로 로그인 버튼 [로그인 브랜드 가이드라인](https://developers.google.com/identity/branding-guidelines?hl=ko) 준수하여 제작
- [ ] Google 로그인은 했지만 42 인증은 하지 않았을 때의 User Flow 설계 (필요하다면 해당 UI 피그마에 추가)

**Comment by yoopark** [comment]
## OAuth란?
> `~로 로그인` 버튼은 모두 OAuth다. 

Open Authorization의 약자로, 우리의 서비스에 Google ID/PW를 직접 입력하여 로그인하는 방식을 해결하기 위해 등장. 

![](https://developers.payco.com/static/img/@img_guide2.jpg)
위 사진에서 1 ~ 9 단계가 로그인 과정에 해당. 

(OAuth 1.0이 Twitter의 주도로 탄생했으며, 불편한 점을 개선하고자 OAuth 2.0 업데이트)

- OAuth 1.0 vs 2.0
![image](https://user-images.githubusercontent.com/61629480/224391602-2fa369f6-b675-47c7-aebf-4754a2264cdf.png)
[표 원본 링크](https://justee.tistory.com/1)

## Google OAuth 사용법
`Google로 로그인` 버튼을 눌렀을 때 다음의 URL로 이동해야 한다. 
```Text
https://accounts.google.com/o/oauth2/auth?
  client_id={Google Cloud Platform에서 만든 서비스 클라이언트 ID}&
  redirect_uri={Google Cloud Platform에 적어놓은 URI, 구글 서버에 사용자 정보를 요청할 BE쪽 주소}&
  response_type=token&
  scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
```

> 아마 위의 URL은 로그인 창 화면일 것이다. 

만약 인증에 성공했다면 Google에서 access_token(맨 위 이미지에서는 Authorization Code에 해당)를 줄텐데 해당 정보를 BE쪽 `redirect_uri`에 전달해준다. (만약 올바른 access_token이라면 BE가 우리에게 로그인 성공 했다고 result를 보내줄 것이다)

**Comment by yoopark** [comment]
## `Google로 로그인` 버튼 가이드라인에 대하여, 

저번에 @jpham005 님이 'Google 계정으로 로그인', '구글 계정으로 로그인', '구글로 로그인'처럼 정확히 정해진 텍스트가 있다고 말씀해주셔서 언급하고 넘어갑니다. 

가이드라인을 찾아본 결과, **Google 계정으로 로그인**이라는 텍스트를 권장하므로 'Google로 로그인'이 아니라 해당 텍스트로 작업하겠습니다.

## 디자인 중요 준수 사항 정리
- 텍스트 왼쪽 및 오른쪽의 여백은 8dp여야 합니다. 
- 로고는 18dp여야 하며, 
- 로고와 버튼 텍스트 사이는 24dp만큼 떨어져 있어야 합니다.
- 높이는 40dp여야 합니다.

![](https://developers.google.com/static/identity/images/google_button_spec.png?hl=ko)

> dp는 Device Independent Pixel(디바이스 크기에 의존하지 않는 픽셀)이라는 뜻으로, 그냥 비율만 맞추라는 뜻입니다.

**Comment by jpham005** [comment]
기존 42 stat은 그냥 구글에서 렌더링 시켜주는거 쓰고,
42로그인은 intra랑 같은 디자인으로 만든것이긴 합니다 ㅋㅋㅋ

다른 아이디어가 떠오른다면 자유롭게 수정해도 좋습니다!

**Comment by yoopark** [comment]
![](https://react-oauth.vercel.app/images/Code-snap.png)

로그인 시 Authorization Code를 보내는 곳은 GraphQL을 사용 못하는 것 아닌가?

**Comment by yoopark** [comment]
BE 인증 엔드포인트 생기면 그때 다시 오픈하겠습니다.

**Comment by yoopark** [comment]
> 2023-06-09 회의에서 논의된 내용을 정리하여 올립니다. 

## 세부 설계 요구사항

- REST API POST가 아닌 GraphQL Mutation 기능을 활용하여 최대한 제작해보기
- 반드시 Google 로그인 -> 42 OAuth 1회 인증으로 강제하기 보다는, 매번 42 OAuth 하나만으로도 로그인할 수 있도록 플로우 다변화
- JWT를 localStorage에 저장하는 방식이 아니라 세션 키를 sessionStorage에 저장하는 방식으로 보안 강화하기
- Refresh Token을 사용할지 여부 결정하기 : Best Practice 잘 찾아보기
- Google 인증은 OpenID 방식, 42 OAuth는 OAuth 2.0 (이거밖에 없음) 방식으로 구현하기

## 이전 42스탯 Reference

### FE 로그인 로직
![](https://raw.githubusercontent.com/42Stat/42Stat/41fc6f80d5b33eff81bea3ca609da95cd3675647/docs/FrontLoginLogic.svg)

### BE 로그인 로직
![](https://raw.githubusercontent.com/42Stat/42Stat/41fc6f80d5b33eff81bea3ca609da95cd3675647/docs/BackendLoginLogic.svg)

- 기존 방식은 Google 로그인만 해도 유저를 생성하고 42Stat 서비스 내부로 들어올 수 있는 access_token을 부여함. 
- 하지만 JWT 내부에 `needFtOAuth: true`로 설정되어 있어 바로 리다이렉트 되는 방식. 
- 42 인증을 하면 새로운 access_token으로 덮어씌워진다. 

### 의문점
1. JWT 조작 불가능한가?
2. needFtOAuth 같은 핵심 정보를 FE에서 까서 리다이렉션하는게 보안상 괜찮은가? 

## TODO

### Must have
- [ ] 위 이미지처럼 유저 플로우 제작하기
- [ ] 발생할 수 있는 모든 시나리오에 대해 Figma에 페이지 제작하기

### Should have
- [ ] BE에서 유저 어떻게 저장하면 좋을지 (새로운 table 생성 여부) 구상해보기

### Could have
- [ ] Mock Server 사용하여 실제로 기능 돌아가도록 제작하기

**Comment by jpham005** [comment]
의문점에 대해선,
1. 서버쪽에서만 가능 (그렇기때문에 jwt 를 사용하는거죠)
2. decoding 은 어차피 secret 없이 되기 때문에, 애초에 jwt 에 포함시킬지 여부가 중요한거긴 합니다. 보안적으로 위험한 정보는 jwt로 사용하면 안되는거죠.
